name: Discord Bot Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Set Environment Variables
        run: echo "BOT_TOKEN=your_bot_token_here" >> .env
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Run Bot
        run: node your_file_name.js
